name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ 
secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME 
}}/whalesay-image:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME 
}}/whalesay-image:latest
name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t whalesay-image .

      - name: Run Docker container
        run: |
          docker run --rm whalesay-image cowsay "Hello from Jenkins!"

      - name: Push Docker image
        run: |
          docker tag whalesay-image:latest yourdockerhubusername/whalesay-image:latest
          docker push yourdockerhubusername/whalesay-image:latest
